export const LAUNCHER_ICON_VISUAL_FRAME_CLASS_V1 = "shadow-lg";
export const LAUNCHER_ICON_VISUAL_SIZE_CLASS_V1 = "h-14 w-14";
export const LAUNCHER_ICON_VISUAL_CLASS_V1 =
    `${LAUNCHER_ICON_VISUAL_SIZE_CLASS_V1} ${LAUNCHER_ICON_VISUAL_FRAME_CLASS_V1}`;
export const LAUNCHER_ICON_VISUAL_INTERACTIVE_CLASS_V1 = "transition-shadow hover:shadow-xl";
export const LAUNCHER_ICON_VISUAL_LARGE_CLASS_V1 = `h-20 w-20 ${LAUNCHER_ICON_VISUAL_FRAME_CLASS_V1}`;
